# Generated by Django 4.0.6 on 2023-01-26 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
