# Generated by Django 4.0.6 on 2023-01-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thelab_backend', '0002_companyname_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
