# Generated by Django 4.0.6 on 2023-01-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thelab_backend', '0004_alter_companyname_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyname',
            options={'managed': True},
        ),
    ]
